---
- name : Uninstall webserver
  hosts: web
  become: true
  tasks:
    - name: Stop and disable nginx at boot
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: false

    - name: Uninstall nginx
      ansible.builtin.package:
        name: nginx
        state: absent
