---
  - name: Use Ansible Vault
    hosts: db
    become: true
    vars_files:
      - vault.yml
    tasks:
      - name: Ensure MariaDB-server is installed.
        ansible.builtin.package:
          name: mariadb-server
          state: present

      - name: Ensure PyMySQL is installed
        ansible.builtin.package:
          name: python3-PyMySQL
          state: present

      - name: Ensure MariaDB is started and enabled
        ansible.builtin.service:
          name: mariadb
          enabled: true
          state: started

      - name: Create webappdb database
        community.mysql.mysql_db:
          name: webappdb
          state: present
          login_unix_socket: /var/lib/mysql/mysql.sock
        register: db_create_result

      - name: Show DB result
        ansible.builtin.debug:
          var: db_create_result 

      - name: Create webappuser with full access to webappdb
        community.mysql.mysql_user:
          name: webappuser
          password: "{{ webappdb_password }}"
          priv: 'webappdb.*:ALL'
          state: present
          login_unix_socket: /var/lib/mysql/mysql.sock


