---
# tasks file for dbserver

- name: Ensure MariaDB server is installed
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Ensure PyMySQL is installed
  ansible.builtin.package:
    name: python3-PyMySQL
    state: present

- name: Ensure MariaDB is started and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Create database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  register: db_create_result

- name: Show DB creation result
  ansible.builtin.debug:
    var: db_create_result

- name: Create DB user with privileges
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ webappdb_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Ensure deploy's home directory exists
  ansible.builtin.file:
    path: "{{ deploy_home }}"
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'

- name: Show found .md files
  debug:
    var: item
  with_fileglob:
    - "{{ playbook_dir }}/files/*.md"

- name: Copy .md files to deploy's home directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ deploy_home }}/"
    owner: deploy
    group: deploy
    mode: '0644'
  with_fileglob:
    - "{{ playbook_dir }}/files/*.md"
